# Generated by Django 3.2.9 on 2021-11-29 23:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='instructor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
